### ISSUE TITLE
Default parser does not use FromStr::from_str

### ISSUE THREAD

**Issue by robinhundt** [teloxide/teloxide-macros#8]
Hey all,

according to the BotCommand [docs](https://docs.rs/teloxide/0.3.0/teloxide/utils/command/trait.BotCommand.html#enum-attributes) the default command field parser should use `FromStr::from_str`. Unfortunately this does not seem to be the case.

I have never written a proc macro, but I believe the error is in the declaration of this closure, which simply wraps the argument String `s` from the message in an `Ok((s,))`.
https://github.com/teloxide/teloxide-macros/blob/f5dbfb246c952b3a23c60b1465e260fb69f21052/src/fields_parse.rs#L76

**Comment by robinhundt** [comment]
Just checking if this issue has been noticed here @Hirrolot @p0lunin :)

**Comment by Hirrolot** [comment]
Closed by https://github.com/teloxide/teloxide-macros/pull/9.
